Mh pundit policies
merrillhuang/industrial-auth-1 pull request #2
Opened 2024-10-29 17:25 UTC by merrillhuang

Creating a pull request, ignore for now. Will update after industrial auth branch is merged to make a clean commit history (removing commits from industrial auth branch)

2024-10-29 19:36 UTC, Ritumka approved these changes
Good job!

2024-10-29 19:36 UTC, Ritumka commented on app/policies/follow_request_policy.rb
> +class FollowRequestPolicy < ApplicationPolicy
You did authorization for everything ,cool!

2024-10-29 19:36 UTC, Ritumka commented on app/policies/user_policy.rb
> +end
Policies look good!

2024-10-30 20:48 UTC, armstrca requested changes
Alice does not seem to be able to delete her own comments, though she can create/edit/update them.

2024-10-30 21:25 UTC, merrillhuang commented
> Alice does not seem to be able to delete her own comments, though she can create/edit/update them.

Made change to allow deleting user's own comments. Removed checking is_an_authorized_user on destroy comments. Allows comment destroy to be authorized using pundit policies instead.

2024-10-30 21:49 UTC, armstrca approved these changes
Looks good. Don't merge this before you merge the previous branch, though.

2024-11-04 17:59 UTC, merged